server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/auth/**

        - id: production-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/prod/**

        - id: sales-service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/sales/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
